/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import ABB.ABBHistorial;
import Hashtable.Client;
import Hashtable.Lista;
import javax.swing.JOptionPane;

/**
 *
 * @author nelsoncarrillo
 */
public class HistorialHabitacion extends javax.swing.JFrame {
    
    private final MenuPrincipal menu;
    private final ABBHistorial historial;
    /**
     * Creates new form HistorialHabitacion
     * @param arbol
     * @param muns
     */
    public HistorialHabitacion(ABBHistorial arbol,MenuPrincipal muns) {
        initComponents();
        setLocationRelativeTo(null);
        hab.setText("");
        datos.setEditable(false);
        datos.setText("");
        setResizable(false);
        this.historial=arbol;
        this.menu=muns;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Atras = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        hab = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datos = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Atras.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Atras.setText("Atrás");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        jPanel1.add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        title.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Historial de Habitación No.");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        hab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habActionPerformed(evt);
            }
        });
        jPanel1.add(hab, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 80, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hab.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 40, -1));

        Buscar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 80, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingrese Número de Habitación para obtener listado de clientes hospedados previamente:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        datos.setColumns(20);
        datos.setFont(new java.awt.Font("Noto Nastaliq Urdu", 1, 13)); // NOI18N
        datos.setRows(5);
        jScrollPane1.setViewportView(datos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 550, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hotels Business Website in Brown White Modern Elegance Style.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        // TODO add your handling code here:
        this.menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AtrasActionPerformed

    private void habActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_habActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        try{
            String habStr = hab.getText().trim();
            int room = Integer.parseInt(habStr);
            if(room<301 && room>0){
            Lista history = historial.searchRoomHis(room, historial.getRoot());
            if (history != null){
                title.setText("Historial de la Habitacion N°"+room);
                String info = "";
                for (int i = 0; i < history.getSize(); i++) {
                    Client cliente = (Client) history.getDato(i).getElement();
                    info += "~ "+cliente.getName()+" "+cliente.getLastName()+" CI: "+cliente.getCedula()+"\n";
                }
                datos.setText(info);
                hab.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Ningun cliente se ha hospedado en esta habitacion");
                hab.setText("");
                title.setText("Historial de la Habitacion N°");
                datos.setText("Ningun cliente se ha hospedado en esta habitacion");
            }} else{
                JOptionPane.showMessageDialog(null, "ERROR - Recuerde ingresar unicamente numeros y que solo\ntenemos 300 habitaciones");    
                hab.setText("");
                title.setText("Historial de la Habitacion N°");
                datos.setText("");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "ERROR - Recuerde ingresar unicamente numeros y que solo\ntenemos 300 habitaciones");
            hab.setText("");
            title.setText("Historial de la Habitacion N°");
            datos.setText("");
        }
    }//GEN-LAST:event_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton Buscar;
    private javax.swing.JTextArea datos;
    private javax.swing.JTextField hab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
